// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateEnvelope struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // protocol version, start at 1
	// Types that are valid to be assigned to Payload:
	//
	//	*StateEnvelope_Full
	//	*StateEnvelope_Delta
	Payload       isStateEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateEnvelope) Reset() {
	*x = StateEnvelope{}
	mi := &file_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateEnvelope) ProtoMessage() {}

func (x *StateEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateEnvelope.ProtoReflect.Descriptor instead.
func (*StateEnvelope) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{0}
}

func (x *StateEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StateEnvelope) GetPayload() isStateEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StateEnvelope) GetFull() *StateFull {
	if x != nil {
		if x, ok := x.Payload.(*StateEnvelope_Full); ok {
			return x.Full
		}
	}
	return nil
}

func (x *StateEnvelope) GetDelta() *StateDelta {
	if x != nil {
		if x, ok := x.Payload.(*StateEnvelope_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

type isStateEnvelope_Payload interface {
	isStateEnvelope_Payload()
}

type StateEnvelope_Full struct {
	Full *StateFull `protobuf:"bytes,2,opt,name=full,proto3,oneof"`
}

type StateEnvelope_Delta struct {
	Delta *StateDelta `protobuf:"bytes,3,opt,name=delta,proto3,oneof"`
}

func (*StateEnvelope_Full) isStateEnvelope_Payload() {}

func (*StateEnvelope_Delta) isStateEnvelope_Payload() {}

type StateFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateFull) Reset() {
	*x = StateFull{}
	mi := &file_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateFull) ProtoMessage() {}

func (x *StateFull) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateFull.ProtoReflect.Descriptor instead.
func (*StateFull) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{1}
}

func (x *StateFull) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type StateDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`                       // changed/new entities
	RemovedIds    []string               `protobuf:"bytes,2,rep,name=removed_ids,json=removedIds,proto3" json:"removed_ids,omitempty"` // entity ids to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateDelta) Reset() {
	*x = StateDelta{}
	mi := &file_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateDelta) ProtoMessage() {}

func (x *StateDelta) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateDelta.ProtoReflect.Descriptor instead.
func (*StateDelta) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{2}
}

func (x *StateDelta) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *StateDelta) GetRemovedIds() []string {
	if x != nil {
		return x.RemovedIds
	}
	return nil
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      int32                  `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"`
	Dexterity     int32                  `protobuf:"varint,2,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Intelligence  int32                  `protobuf:"varint,3,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Wisdom        int32                  `protobuf:"varint,4,opt,name=wisdom,proto3" json:"wisdom,omitempty"`
	Vitality      int32                  `protobuf:"varint,5,opt,name=vitality,proto3" json:"vitality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{3}
}

func (x *Stats) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Stats) GetDexterity() int32 {
	if x != nil {
		return x.Dexterity
	}
	return 0
}

func (x *Stats) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *Stats) GetWisdom() int32 {
	if x != nil {
		return x.Wisdom
	}
	return 0
}

func (x *Stats) GetVitality() int32 {
	if x != nil {
		return x.Vitality
	}
	return 0
}

type Quest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	MaxCount      int32                  `protobuf:"varint,5,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	RewardXp      int32                  `protobuf:"varint,6,opt,name=reward_xp,json=rewardXp,proto3" json:"reward_xp,omitempty"`
	Completed     bool                   `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
	Accepted      bool                   `protobuf:"varint,8,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quest) Reset() {
	*x = Quest{}
	mi := &file_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quest) ProtoMessage() {}

func (x *Quest) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quest.ProtoReflect.Descriptor instead.
func (*Quest) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{4}
}

func (x *Quest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Quest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Quest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Quest) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *Quest) GetRewardXp() int32 {
	if x != nil {
		return x.RewardXp
	}
	return 0
}

func (x *Quest) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Quest) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SocketedGem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Quality       string                 `protobuf:"bytes,2,opt,name=quality,proto3" json:"quality,omitempty"`
	Stats         map[string]int32       `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocketedGem) Reset() {
	*x = SocketedGem{}
	mi := &file_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketedGem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketedGem) ProtoMessage() {}

func (x *SocketedGem) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketedGem.ProtoReflect.Descriptor instead.
func (*SocketedGem) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{5}
}

func (x *SocketedGem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SocketedGem) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *SocketedGem) GetStats() map[string]int32 {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Rarity        string                 `protobuf:"bytes,4,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Slot          string                 `protobuf:"bytes,5,opt,name=slot,proto3" json:"slot,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Stats         map[string]int32       `protobuf:"bytes,7,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Value         int32                  `protobuf:"varint,8,opt,name=value,proto3" json:"value,omitempty"`
	Icon          string                 `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Stack         int32                  `protobuf:"varint,11,opt,name=stack,proto3" json:"stack,omitempty"`
	MaxStack      int32                  `protobuf:"varint,12,opt,name=max_stack,json=maxStack,proto3" json:"max_stack,omitempty"`
	Potency       int32                  `protobuf:"varint,13,opt,name=potency,proto3" json:"potency,omitempty"`
	Sockets       int32                  `protobuf:"varint,14,opt,name=sockets,proto3" json:"sockets,omitempty"`
	GemType       string                 `protobuf:"bytes,15,opt,name=gem_type,json=gemType,proto3" json:"gem_type,omitempty"`
	GemQuality    string                 `protobuf:"bytes,16,opt,name=gem_quality,json=gemQuality,proto3" json:"gem_quality,omitempty"`
	Gems          []*SocketedGem         `protobuf:"bytes,17,rep,name=gems,proto3" json:"gems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{6}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *Item) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *Item) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Item) GetStats() map[string]int32 {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Item) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Item) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetStack() int32 {
	if x != nil {
		return x.Stack
	}
	return 0
}

func (x *Item) GetMaxStack() int32 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *Item) GetPotency() int32 {
	if x != nil {
		return x.Potency
	}
	return 0
}

func (x *Item) GetSockets() int32 {
	if x != nil {
		return x.Sockets
	}
	return 0
}

func (x *Item) GetGemType() string {
	if x != nil {
		return x.GemType
	}
	return ""
}

func (x *Item) GetGemQuality() string {
	if x != nil {
		return x.GemQuality
	}
	return ""
}

func (x *Item) GetGems() []*SocketedGem {
	if x != nil {
		return x.Gems
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	SubType       string                 `protobuf:"bytes,5,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	X             float32                `protobuf:"fixed32,6,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,7,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,8,opt,name=z,proto3" json:"z,omitempty"`
	Rotation      float32                `protobuf:"fixed32,9,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Health        int32                  `protobuf:"varint,10,opt,name=health,proto3" json:"health,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,11,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	Mana          int32                  `protobuf:"varint,12,opt,name=mana,proto3" json:"mana,omitempty"`
	MaxMana       int32                  `protobuf:"varint,13,opt,name=max_mana,json=maxMana,proto3" json:"max_mana,omitempty"`
	Level         int32                  `protobuf:"varint,14,opt,name=level,proto3" json:"level,omitempty"`
	Experience    int32                  `protobuf:"varint,15,opt,name=experience,proto3" json:"experience,omitempty"`
	MaxExperience int32                  `protobuf:"varint,16,opt,name=max_experience,json=maxExperience,proto3" json:"max_experience,omitempty"`
	Gold          int32                  `protobuf:"varint,17,opt,name=gold,proto3" json:"gold,omitempty"`
	// Skills
	SkillPoints    int32    `protobuf:"varint,18,opt,name=skill_points,json=skillPoints,proto3" json:"skill_points,omitempty"`
	SelectedBranch string   `protobuf:"bytes,19,opt,name=selected_branch,json=selectedBranch,proto3" json:"selected_branch,omitempty"`
	UnlockedSkills []string `protobuf:"bytes,20,rep,name=unlocked_skills,json=unlockedSkills,proto3" json:"unlocked_skills,omitempty"`
	// Stats
	BaseStats *Stats `protobuf:"bytes,21,opt,name=base_stats,json=baseStats,proto3" json:"base_stats,omitempty"`
	Stats     *Stats `protobuf:"bytes,22,opt,name=stats,proto3" json:"stats,omitempty"`
	Damage    int32  `protobuf:"varint,23,opt,name=damage,proto3" json:"damage,omitempty"`
	Defense   int32  `protobuf:"varint,24,opt,name=defense,proto3" json:"defense,omitempty"`
	// Derived
	Speed             float32 `protobuf:"fixed32,25,opt,name=speed,proto3" json:"speed,omitempty"`
	AttackSpeed       float32 `protobuf:"fixed32,26,opt,name=attack_speed,json=attackSpeed,proto3" json:"attack_speed,omitempty"`
	CooldownReduction float32 `protobuf:"fixed32,27,opt,name=cooldown_reduction,json=cooldownReduction,proto3" json:"cooldown_reduction,omitempty"`
	HpRegen           float32 `protobuf:"fixed32,28,opt,name=hp_regen,json=hpRegen,proto3" json:"hp_regen,omitempty"`
	ManaRegen         float32 `protobuf:"fixed32,29,opt,name=mana_regen,json=manaRegen,proto3" json:"mana_regen,omitempty"`
	CastSpeed         float32 `protobuf:"fixed32,30,opt,name=cast_speed,json=castSpeed,proto3" json:"cast_speed,omitempty"`
	Scale             float32 `protobuf:"fixed32,31,opt,name=scale,proto3" json:"scale,omitempty"`
	// Core state
	State string `protobuf:"bytes,32,opt,name=state,proto3" json:"state,omitempty"`
	// Equipment + quests (inventory is sent via separate messages in current server model)
	Equipment map[string]*Item `protobuf:"bytes,33,rep,name=equipment,proto3" json:"equipment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Quests    []*Quest         `protobuf:"bytes,34,rep,name=quests,proto3" json:"quests,omitempty"`
	// Loot
	LootItem *Item `protobuf:"bytes,35,opt,name=loot_item,json=lootItem,proto3" json:"loot_item,omitempty"`
	// Projectile
	OwnerId string  `protobuf:"bytes,36,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	VelX    float32 `protobuf:"fixed32,37,opt,name=vel_x,json=velX,proto3" json:"vel_x,omitempty"`
	VelZ    float32 `protobuf:"fixed32,38,opt,name=vel_z,json=velZ,proto3" json:"vel_z,omitempty"`
	// Ability flags (subset)
	SpiritsActive  bool `protobuf:"varint,39,opt,name=spirits_active,json=spiritsActive,proto3" json:"spirits_active,omitempty"`
	SpiritsBoosted bool `protobuf:"varint,40,opt,name=spirits_boosted,json=spiritsBoosted,proto3" json:"spirits_boosted,omitempty"`
	IsCharging     bool `protobuf:"varint,41,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	GuardianEmbraceActive bool `protobuf:"varint,51,opt,name=guardian_embrace_active,json=guardianEmbraceActive,proto3" json:"guardian_embrace_active,omitempty"`
	BlessingResolveActive bool `protobuf:"varint,52,opt,name=blessing_resolve_active,json=blessingResolveActive,proto3" json:"blessing_resolve_active,omitempty"`
	DivineInterventionActive bool `protobuf:"varint,53,opt,name=divine_intervention_active,json=divineInterventionActive,proto3" json:"divine_intervention_active,omitempty"`
	ArcaneShieldActive bool `protobuf:"varint,54,opt,name=arcane_shield_active,json=arcaneShieldActive,proto3" json:"arcane_shield_active,omitempty"`
	ArcaneShieldHp int32 `protobuf:"varint,55,opt,name=arcane_shield_hp,json=arcaneShieldHp,proto3" json:"arcane_shield_hp,omitempty"`
	TimeWarpActive bool `protobuf:"varint,56,opt,name=time_warp_active,json=timeWarpActive,proto3" json:"time_warp_active,omitempty"`
	SpellFocusActive bool `protobuf:"varint,57,opt,name=spell_focus_active,json=spellFocusActive,proto3" json:"spell_focus_active,omitempty"`
	// Common buff/debuff booleans used for visuals/behavior
	Stunned  bool `protobuf:"varint,42,opt,name=stunned,proto3" json:"stunned,omitempty"`
	Slowed   bool `protobuf:"varint,43,opt,name=slowed,proto3" json:"slowed,omitempty"`
	Rooted   bool `protobuf:"varint,44,opt,name=rooted,proto3" json:"rooted,omitempty"`
	Bleeding bool `protobuf:"varint,45,opt,name=bleeding,proto3" json:"bleeding,omitempty"`
	Poisoned bool `protobuf:"varint,46,opt,name=poisoned,proto3" json:"poisoned,omitempty"`
	SlowFactor float32 `protobuf:"fixed32,58,opt,name=slow_factor,json=slowFactor,proto3" json:"slow_factor,omitempty"`
	RootDuration float32 `protobuf:"fixed32,59,opt,name=root_duration,json=rootDuration,proto3" json:"root_duration,omitempty"`
	StunDuration float32 `protobuf:"fixed32,60,opt,name=stun_duration,json=stunDuration,proto3" json:"stun_duration,omitempty"`
	BleedDuration float32 `protobuf:"fixed32,61,opt,name=bleed_duration,json=bleedDuration,proto3" json:"bleed_duration,omitempty"`
	// Passive talents
	TalentPoints    int32    `protobuf:"varint,47,opt,name=talent_points,json=talentPoints,proto3" json:"talent_points,omitempty"`
	UnlockedTalents []string `protobuf:"bytes,48,rep,name=unlocked_talents,json=unlockedTalents,proto3" json:"unlocked_talents,omitempty"`
	// Ranked passive talents: talentId -> rank.
	// New clients should use this; unlocked_talents is retained for backwards compatibility.
	TalentRanks map[string]int32 `protobuf:"bytes,49,rep,name=talent_ranks,json=talentRanks,proto3" json:"talent_ranks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Skill runes: skillName -> runeId
	SkillRunes    map[string]string `protobuf:"bytes,50,rep,name=skill_runes,json=skillRunes,proto3" json:"skill_runes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_state_proto_rawDescGZIP(), []int{7}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetSubType() string {
	if x != nil {
		return x.SubType
	}
	return ""
}

func (x *Entity) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Entity) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Entity) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Entity) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Entity) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Entity) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *Entity) GetMana() int32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *Entity) GetMaxMana() int32 {
	if x != nil {
		return x.MaxMana
	}
	return 0
}

func (x *Entity) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Entity) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *Entity) GetMaxExperience() int32 {
	if x != nil {
		return x.MaxExperience
	}
	return 0
}

func (x *Entity) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *Entity) GetSkillPoints() int32 {
	if x != nil {
		return x.SkillPoints
	}
	return 0
}

func (x *Entity) GetSelectedBranch() string {
	if x != nil {
		return x.SelectedBranch
	}
	return ""
}

func (x *Entity) GetUnlockedSkills() []string {
	if x != nil {
		return x.UnlockedSkills
	}
	return nil
}

func (x *Entity) GetBaseStats() *Stats {
	if x != nil {
		return x.BaseStats
	}
	return nil
}

func (x *Entity) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Entity) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Entity) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *Entity) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Entity) GetAttackSpeed() float32 {
	if x != nil {
		return x.AttackSpeed
	}
	return 0
}

func (x *Entity) GetCooldownReduction() float32 {
	if x != nil {
		return x.CooldownReduction
	}
	return 0
}

func (x *Entity) GetHpRegen() float32 {
	if x != nil {
		return x.HpRegen
	}
	return 0
}

func (x *Entity) GetManaRegen() float32 {
	if x != nil {
		return x.ManaRegen
	}
	return 0
}

func (x *Entity) GetCastSpeed() float32 {
	if x != nil {
		return x.CastSpeed
	}
	return 0
}

func (x *Entity) GetScale() float32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Entity) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Entity) GetEquipment() map[string]*Item {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *Entity) GetQuests() []*Quest {
	if x != nil {
		return x.Quests
	}
	return nil
}

func (x *Entity) GetLootItem() *Item {
	if x != nil {
		return x.LootItem
	}
	return nil
}

func (x *Entity) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Entity) GetVelX() float32 {
	if x != nil {
		return x.VelX
	}
	return 0
}

func (x *Entity) GetVelZ() float32 {
	if x != nil {
		return x.VelZ
	}
	return 0
}

func (x *Entity) GetSpiritsActive() bool {
	if x != nil {
		return x.SpiritsActive
	}
	return false
}

func (x *Entity) GetSpiritsBoosted() bool {
	if x != nil {
		return x.SpiritsBoosted
	}
	return false
}

func (x *Entity) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *Entity) GetGuardianEmbraceActive() bool {
	if x != nil {
		return x.GuardianEmbraceActive
	}
	return false
}

func (x *Entity) GetBlessingResolveActive() bool {
	if x != nil {
		return x.BlessingResolveActive
	}
	return false
}

func (x *Entity) GetDivineInterventionActive() bool {
	if x != nil {
		return x.DivineInterventionActive
	}
	return false
}

func (x *Entity) GetArcaneShieldActive() bool {
	if x != nil {
		return x.ArcaneShieldActive
	}
	return false
}

func (x *Entity) GetArcaneShieldHp() int32 {
	if x != nil {
		return x.ArcaneShieldHp
	}
	return 0
}

func (x *Entity) GetTimeWarpActive() bool {
	if x != nil {
		return x.TimeWarpActive
	}
	return false
}

func (x *Entity) GetSpellFocusActive() bool {
	if x != nil {
		return x.SpellFocusActive
	}
	return false
}

func (x *Entity) GetStunned() bool {
	if x != nil {
		return x.Stunned
	}
	return false
}

func (x *Entity) GetSlowed() bool {
	if x != nil {
		return x.Slowed
	}
	return false
}

func (x *Entity) GetRooted() bool {
	if x != nil {
		return x.Rooted
	}
	return false
}

func (x *Entity) GetBleeding() bool {
	if x != nil {
		return x.Bleeding
	}
	return false
}

func (x *Entity) GetPoisoned() bool {
	if x != nil {
		return x.Poisoned
	}
	return false
}

func (x *Entity) GetSlowFactor() float32 {
	if x != nil {
		return x.SlowFactor
	}
	return 0
}

func (x *Entity) GetRootDuration() float32 {
	if x != nil {
		return x.RootDuration
	}
	return 0
}

func (x *Entity) GetStunDuration() float32 {
	if x != nil {
		return x.StunDuration
	}
	return 0
}

func (x *Entity) GetBleedDuration() float32 {
	if x != nil {
		return x.BleedDuration
	}
	return 0
}

func (x *Entity) GetTalentPoints() int32 {
	if x != nil {
		return x.TalentPoints
	}
	return 0
}

func (x *Entity) GetUnlockedTalents() []string {
	if x != nil {
		return x.UnlockedTalents
	}
	return nil
}

func (x *Entity) GetTalentRanks() map[string]int32 {
	if x != nil {
		return x.TalentRanks
	}
	return nil
}

func (x *Entity) GetSkillRunes() map[string]string {
	if x != nil {
		return x.SkillRunes
	}
	return nil
}

var File_state_proto protoreflect.FileDescriptor

const file_state_proto_rawDesc = "" +
	"\n" +
	"\vstate.proto\x12\reidolon.state\"\x97\x01\n" +
	"\rStateEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12.\n" +
	"\x04full\x18\x02 \x01(\v2\x18.eidolon.state.StateFullH\x00R\x04full\x121\n" +
	"\x05delta\x18\x03 \x01(\v2\x19.eidolon.state.StateDeltaH\x00R\x05deltaB\t\n" +
	"\apayload\">\n" +
	"\tStateFull\x121\n" +
	"\bentities\x18\x01 \x03(\v2\x15.eidolon.state.EntityR\bentities\"`\n" +
	"\n" +
	"StateDelta\x121\n" +
	"\bentities\x18\x01 \x03(\v2\x15.eidolon.state.EntityR\bentities\x12\x1f\n" +
	"\vremoved_ids\x18\x02 \x03(\tR\n" +
	"removedIds\"\x99\x01\n" +
	"\x05Stats\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x05R\bstrength\x12\x1c\n" +
	"\tdexterity\x18\x02 \x01(\x05R\tdexterity\x12\"\n" +
	"\fintelligence\x18\x03 \x01(\x05R\fintelligence\x12\x16\n" +
	"\x06wisdom\x18\x04 \x01(\x05R\x06wisdom\x12\x1a\n" +
	"\bvitality\x18\x05 \x01(\x05R\bvitality\"\xcd\x01\n" +
	"\x05Quest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1b\n" +
	"\tmax_count\x18\x05 \x01(\x05R\bmaxCount\x12\x1b\n" +
	"\treward_xp\x18\x06 \x01(\x05R\brewardXp\x12\x1c\n" +
	"\tcompleted\x18\a \x01(\bR\tcompleted\x12\x1a\n" +
	"\baccepted\x18\b \x01(\bR\baccepted\"\xb2\x01\n" +
	"\vSocketedGem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aquality\x18\x02 \x01(\tR\aquality\x12;\n" +
	"\x05stats\x18\x03 \x03(\v2%.eidolon.state.SocketedGem.StatsEntryR\x05stats\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x8f\x04\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06rarity\x18\x04 \x01(\tR\x06rarity\x12\x12\n" +
	"\x04slot\x18\x05 \x01(\tR\x04slot\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x124\n" +
	"\x05stats\x18\a \x03(\v2\x1e.eidolon.state.Item.StatsEntryR\x05stats\x12\x14\n" +
	"\x05value\x18\b \x01(\x05R\x05value\x12\x12\n" +
	"\x04icon\x18\t \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x14\n" +
	"\x05stack\x18\v \x01(\x05R\x05stack\x12\x1b\n" +
	"\tmax_stack\x18\f \x01(\x05R\bmaxStack\x12\x18\n" +
	"\apotency\x18\r \x01(\x05R\apotency\x12\x18\n" +
	"\asockets\x18\x0e \x01(\x05R\asockets\x12\x19\n" +
	"\bgem_type\x18\x0f \x01(\tR\agemType\x12\x1f\n" +
	"\vgem_quality\x18\x10 \x01(\tR\n" +
	"gemQuality\x12.\n" +
	"\x04gems\x18\x11 \x03(\v2\x1a.eidolon.state.SocketedGemR\x04gems\x1a8\n" +
	"\n" +
	"StatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9f\x0e\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x19\n" +
	"\bsub_type\x18\x05 \x01(\tR\asubType\x12\f\n" +
	"\x01x\x18\x06 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\a \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\b \x01(\x02R\x01z\x12\x1a\n" +
	"\brotation\x18\t \x01(\x02R\brotation\x12\x16\n" +
	"\x06health\x18\n" +
	" \x01(\x05R\x06health\x12\x1d\n" +
	"\n" +
	"max_health\x18\v \x01(\x05R\tmaxHealth\x12\x12\n" +
	"\x04mana\x18\f \x01(\x05R\x04mana\x12\x19\n" +
	"\bmax_mana\x18\r \x01(\x05R\amaxMana\x12\x14\n" +
	"\x05level\x18\x0e \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x0f \x01(\x05R\n" +
	"experience\x12%\n" +
	"\x0emax_experience\x18\x10 \x01(\x05R\rmaxExperience\x12\x12\n" +
	"\x04gold\x18\x11 \x01(\x05R\x04gold\x12!\n" +
	"\fskill_points\x18\x12 \x01(\x05R\vskillPoints\x12'\n" +
	"\x0fselected_branch\x18\x13 \x01(\tR\x0eselectedBranch\x12'\n" +
	"\x0funlocked_skills\x18\x14 \x03(\tR\x0eunlockedSkills\x123\n" +
	"\n" +
	"base_stats\x18\x15 \x01(\v2\x14.eidolon.state.StatsR\tbaseStats\x12*\n" +
	"\x05stats\x18\x16 \x01(\v2\x14.eidolon.state.StatsR\x05stats\x12\x16\n" +
	"\x06damage\x18\x17 \x01(\x05R\x06damage\x12\x18\n" +
	"\adefense\x18\x18 \x01(\x05R\adefense\x12\x14\n" +
	"\x05speed\x18\x19 \x01(\x02R\x05speed\x12!\n" +
	"\fattack_speed\x18\x1a \x01(\x02R\vattackSpeed\x12-\n" +
	"\x12cooldown_reduction\x18\x1b \x01(\x02R\x11cooldownReduction\x12\x19\n" +
	"\bhp_regen\x18\x1c \x01(\x02R\ahpRegen\x12\x1d\n" +
	"\n" +
	"mana_regen\x18\x1d \x01(\x02R\tmanaRegen\x12\x1d\n" +
	"\n" +
	"cast_speed\x18\x1e \x01(\x02R\tcastSpeed\x12\x14\n" +
	"\x05scale\x18\x1f \x01(\x02R\x05scale\x12\x14\n" +
	"\x05state\x18  \x01(\tR\x05state\x12B\n" +
	"\tequipment\x18! \x03(\v2$.eidolon.state.Entity.EquipmentEntryR\tequipment\x12,\n" +
	"\x06quests\x18\" \x03(\v2\x14.eidolon.state.QuestR\x06quests\x120\n" +
	"\tloot_item\x18# \x01(\v2\x13.eidolon.state.ItemR\blootItem\x12\x19\n" +
	"\bowner_id\x18$ \x01(\tR\aownerId\x12\x13\n" +
	"\x05vel_x\x18% \x01(\x02R\x04velX\x12\x13\n" +
	"\x05vel_z\x18& \x01(\x02R\x04velZ\x12%\n" +
	"\x0espirits_active\x18' \x01(\bR\rspiritsActive\x12'\n" +
	"\x0fspirits_boosted\x18( \x01(\bR\x0espiritsBoosted\x12\x1f\n" +
	"\vis_charging\x18) \x01(\bR\n" +
	"isCharging\x12\x18\n" +
	"\astunned\x18* \x01(\bR\astunned\x12\x16\n" +
	"\x06slowed\x18+ \x01(\bR\x06slowed\x12\x16\n" +
	"\x06rooted\x18, \x01(\bR\x06rooted\x12\x1a\n" +
	"\bbleeding\x18- \x01(\bR\bbleeding\x12\x1a\n" +
	"\bpoisoned\x18. \x01(\bR\bpoisoned\x12#\n" +
	"\rtalent_points\x18/ \x01(\x05R\ftalentPoints\x12)\n" +
	"\x10unlocked_talents\x180 \x03(\tR\x0funlockedTalents\x12I\n" +
	"\ftalent_ranks\x181 \x03(\v2&.eidolon.state.Entity.TalentRanksEntryR\vtalentRanks\x12F\n" +
	"\vskill_runes\x182 \x03(\v2%.eidolon.state.Entity.SkillRunesEntryR\n" +
	"skillRunes\x1aQ\n" +
	"\x0eEquipmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.eidolon.state.ItemR\x05value:\x028\x01\x1a>\n" +
	"\x10TalentRanksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fSkillRunesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B%Z#eidolon-server/internal/proto;protob\x06proto3"

var (
	file_state_proto_rawDescOnce sync.Once
	file_state_proto_rawDescData []byte
)

func file_state_proto_rawDescGZIP() []byte {
	file_state_proto_rawDescOnce.Do(func() {
		file_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)))
	})
	return file_state_proto_rawDescData
}

var file_state_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_state_proto_goTypes = []any{
	(*StateEnvelope)(nil), // 0: eidolon.state.StateEnvelope
	(*StateFull)(nil),     // 1: eidolon.state.StateFull
	(*StateDelta)(nil),    // 2: eidolon.state.StateDelta
	(*Stats)(nil),         // 3: eidolon.state.Stats
	(*Quest)(nil),         // 4: eidolon.state.Quest
	(*SocketedGem)(nil),   // 5: eidolon.state.SocketedGem
	(*Item)(nil),          // 6: eidolon.state.Item
	(*Entity)(nil),        // 7: eidolon.state.Entity
	nil,                   // 8: eidolon.state.SocketedGem.StatsEntry
	nil,                   // 9: eidolon.state.Item.StatsEntry
	nil,                   // 10: eidolon.state.Entity.EquipmentEntry
	nil,                   // 11: eidolon.state.Entity.TalentRanksEntry
	nil,                   // 12: eidolon.state.Entity.SkillRunesEntry
}
var file_state_proto_depIdxs = []int32{
	1,  // 0: eidolon.state.StateEnvelope.full:type_name -> eidolon.state.StateFull
	2,  // 1: eidolon.state.StateEnvelope.delta:type_name -> eidolon.state.StateDelta
	7,  // 2: eidolon.state.StateFull.entities:type_name -> eidolon.state.Entity
	7,  // 3: eidolon.state.StateDelta.entities:type_name -> eidolon.state.Entity
	8,  // 4: eidolon.state.SocketedGem.stats:type_name -> eidolon.state.SocketedGem.StatsEntry
	9,  // 5: eidolon.state.Item.stats:type_name -> eidolon.state.Item.StatsEntry
	5,  // 6: eidolon.state.Item.gems:type_name -> eidolon.state.SocketedGem
	3,  // 7: eidolon.state.Entity.base_stats:type_name -> eidolon.state.Stats
	3,  // 8: eidolon.state.Entity.stats:type_name -> eidolon.state.Stats
	10, // 9: eidolon.state.Entity.equipment:type_name -> eidolon.state.Entity.EquipmentEntry
	4,  // 10: eidolon.state.Entity.quests:type_name -> eidolon.state.Quest
	6,  // 11: eidolon.state.Entity.loot_item:type_name -> eidolon.state.Item
	11, // 12: eidolon.state.Entity.talent_ranks:type_name -> eidolon.state.Entity.TalentRanksEntry
	12, // 13: eidolon.state.Entity.skill_runes:type_name -> eidolon.state.Entity.SkillRunesEntry
	6,  // 14: eidolon.state.Entity.EquipmentEntry.value:type_name -> eidolon.state.Item
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_state_proto_init() }
func file_state_proto_init() {
	if File_state_proto != nil {
		return
	}
	file_state_proto_msgTypes[0].OneofWrappers = []any{
		(*StateEnvelope_Full)(nil),
		(*StateEnvelope_Delta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_proto_rawDesc), len(file_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_state_proto_goTypes,
		DependencyIndexes: file_state_proto_depIdxs,
		MessageInfos:      file_state_proto_msgTypes,
	}.Build()
	File_state_proto = out.File
	file_state_proto_goTypes = nil
	file_state_proto_depIdxs = nil
}
